[469.437122345] 2019-01-03 14:25:53,435 - INFO - launcher: Starting sanity checks
[470.438241959] 2019-01-03 14:25:53,436 - INFO - launcher: Checking for Python 3.5+
[471.436500549] 2019-01-03 14:25:53,437 - INFO - launcher: Checking console encoding
[471.436500549] 2019-01-03 14:25:53,437 - INFO - launcher: Setting console encoding to UTF-8
[471.436500549] 2019-01-03 14:25:53,437 - INFO - launcher: Ensuring we're in the right environment
[475.435733795] 2019-01-03 14:25:53,441 - INFO - launcher: Adding local bins/ folder to path
[8034.668684006] 2019-01-03 14:26:01,000 - INFO - launcher: Required checks passed.
[8045.666456223] 2019-01-03 14:26:01,011 - INFO - launcher: Optional checks passed.
[8046.669006348] 2019-01-03 14:26:01,013 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[29.2339198589324951] 2019-01-03 14:26:22,200 - WARNING - musicbot.config | In config.py::MainThread(10528), line 115 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[29.2349050045013428] 2019-01-03 14:26:22,201 - INFO - musicbot.config | In config.py::MainThread(10528), line 126 in run_checks: Using i18n: config/i18n/en.json
[29.2480249404907227] 2019-01-03 14:26:22,214 - DEBUG - musicbot.bot | In bot.py::MainThread(10528), line 219 in _setup_logging: Set logging level to INFO
[29.2692656517028809] 2019-01-03 14:26:22,235 - DEBUG - musicbot.json | In json.py::MainThread(10528), line 8 in __init__: Init JSON obj with config/i18n/en.json
[30.1765162944793701] 2019-01-03 14:26:23,142 - INFO - musicbot.bot | In bot.py::MainThread(10528), line 84 in __init__: Starting MusicBot 1.9.8_3
[30.3155157566070557] 2019-01-03 14:26:23,281 - WARNING - musicbot.bot | In bot.py::MainThread(10528), line 87 in __init__: Autoplaylist is empty, disabling.
[33.2468185424804688] 2019-01-03 14:26:26,213 - DEBUG - musicbot.bot | In bot.py::MainThread(10528), line 915 in on_ready: Connection established, ready to go.
[33.2478187084197998] 2019-01-03 14:26:26,214 - DEBUG - musicbot.bot | In bot.py::MainThread(10528), line 333 in _cache_app_info: Caching app info
[33.3803062438964844] 2019-01-03 14:26:26,346 - DEBUG - musicbot.bot | In bot.py::MainThread(10528), line 737 in _scheck_ensure_env: Ensuring data folders exist
[33.3933053016662598] 2019-01-03 14:26:26,359 - DEBUG - musicbot.bot | In bot.py::MainThread(10528), line 753 in _scheck_server_permissions: Checking server permissions
[33.3943064212799072] 2019-01-03 14:26:26,360 - DEBUG - musicbot.bot | In bot.py::MainThread(10528), line 757 in _scheck_autoplaylist: Auditing autoplaylist
[33.3943064212799072] 2019-01-03 14:26:26,360 - DEBUG - musicbot.bot | In bot.py::MainThread(10528), line 761 in _scheck_configs: Validating config
[33.3943064212799072] 2019-01-03 14:26:26,360 - DEBUG - musicbot.config | In config.py::MainThread(10528), line 216 in async_validate: Validating options...
[33.3943064212799072] 2019-01-03 14:26:26,360 - DEBUG - musicbot.bot | In bot.py::MainThread(10528), line 764 in _scheck_configs: Validating permissions config
[33.3953082561492920] 2019-01-03 14:26:26,361 - DEBUG - musicbot.permissions | In permissions.py::MainThread(10528), line 94 in async_validate: Validating permissions...
[33.3953082561492920] 2019-01-03 14:26:26,361 - INFO - musicbot.bot | In bot.py::MainThread(10528), line 932 in on_ready: Connected: 530334795331272704/JA Music [ALPHA]#1758
[33.3963065147399902] 2019-01-03 14:26:26,362 - INFO - musicbot.bot | In bot.py::MainThread(10528), line 940 in on_ready: Owner:     404689851716206602/Nisar#7302

[33.3973078727722168] 2019-01-03 14:26:26,363 - INFO - musicbot.bot | In bot.py::MainThread(10528), line 943 in on_ready: Guild List:
[33.3983049392700195] 2019-01-03 14:26:26,364 - INFO - musicbot.bot | In bot.py::MainThread(10528), line 947 in on_ready:  - JA GANG
[33.4023084640502930] 2019-01-03 14:26:26,368 - INFO - musicbot.bot | In bot.py::MainThread(10528), line 1003 in on_ready: Not bound to any text channels
[33.4043066501617432] 2019-01-03 14:26:26,370 - INFO - musicbot.bot | In bot.py::MainThread(10528), line 1029 in on_ready: Not autojoining any voice channels
